[package]
name = "axum-gate"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Lewin Probst <info@emirror.de>"]
description = "JWT auth with role based access for axum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = { version = "0.5.3", features = ["std"] }
axum = "0.8.3"
axum-extra = { version = "0.10.1", features = ["cookie"] }
chrono = { version = "0.4.40", features = ["serde"] }
http = "1.3.1"
jsonwebtoken = "9.3.1"
pin-project = "1.1.10"
rand = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_with = "3.12.0"
thiserror = "2.0.12"
tokio = { version = "1", features = ["full"] }
tokio-test = "0.4.4"
tower = "0.5.2"
tracing = { version = "0.1.41", features = ["release_max_level_off"] }
tracing-attributes = "0.1.28"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["std", "env-filter"] }
