[package]
name = "axum-gate"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Lewin Probst <info@emirror.de>"]
description = "JWT auth with role based access for axum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = { version = "0.5.3", features = ["std"] }
chrono = { version = "0.4.40", features = ["serde"] }
jsonwebtoken = "9.3.1"
rand = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
tracing = { version = "0.1.41", features = ["release_max_level_off"] }
