[package]
name = "axum-gate"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Lewin Probst <info@emirror.de>"]
description = "Role based access for axum using JWT cookies. For both, single nodes and distributed systems."
homepage = "https://github.com/emirror-de/axum-gate"
repository = "https://github.com/emirror-de/axum-gate"
readme = "README.md"
keywords = ["auth", "distributed", "JWT", "axum", "login"]
categories = ["authentication", "web-programming"]

[features]
storage-surrealdb = ["surrealdb"]
storage-seaorm = ["sea-orm/uuid"]

[dependencies]
anyhow = "1.0.98"
argon2 = { version = "0.5.3", features = ["std"] }
axum = "0.8.3"
axum-extra = { version = "0.10.1", features = ["cookie"] }
chrono = { version = "0.4.40", features = ["serde"] }
cookie = { version = "0.18" }
http = "1.3.1"
jsonwebtoken = "9.3.1"
pin-project = "1.1.10"
rand = "0.9.0"
roaring = { version = "0.10.12", features = ["serde"] }
sea-orm = { version = "1", optional = true }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_with = "3.12.0"
strum = { version = "0.27.1", features = ["derive"] }
surrealdb = { version = "2", optional = true }
thiserror = "2.0.12"
tokio = { version = "1", features = ["sync"] }
tower = "0.5.2"
tracing = { version = "0.1.41", features = ["release_max_level_info"] }
uuid = { version = "1", features = ["serde", "v7"] }

[dev-dependencies]
surrealdb = { version = "2", features = ["kv-mem"] }
tracing-subscriber = { version = "0.3", features = ["std", "env-filter"] }
tokio-test = "0.4.4"
uuid = "1"

[profile.dev]
debug = false
