[workspace]
members = [
    "crates/axum-gate",
    "examples/custom-roles",
    "examples/distributed",
    "examples/permission-validation",
    "examples/rate-limiting",
    "examples/sea-orm",
    "examples/simple-usage",
    "examples/surrealdb",
]
resolver = "2"

[workspace.package]
version = "1.0.0"
