[package]
name = "distributed"
version = "0.1.0"
edition = "2024"
default-run = "auth_node"

[[bin]]
name = "auth_node"

[[bin]]
name = "consumer_node"

[dependencies]
axum = "0.8.3"
axum-gate = { path = "../.." }
dotenv = "0.15.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
