[package]
name = "permission-validation-example"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
axum-gate = { path = "../../" }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
